# Generated by Django 6.0.4 on 2026-04-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='step_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
