# Generated by Django 6.0.4 on 2026-04-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_session_metadata_session_step_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('ai_inquiry', 'AI Inquiry')], max_length=20),
        ),
    ]
